name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Testing
        run: |
          npm run build